---
title:
output: html_document
---

```{r}

wine_data1 <- read.csv("winequality-white.csv", sep = ";")
wine_data2 <- read.csv("winequality-red.csv", sep = ";")
sapply(wine_data1,class)
sapply(wine_data2, class)
```

```{r}

sum(is.na(wine_data1))
sum(is.na(wine_data2))
```

```{r}

library(corrplot)
correlation1 = cor(wine_data1[-12])
correlation1
corrplot(correlation1)
correlation2 = cor(wine_data2[-12])
correlation2
corrplot(correlation2)
```
```{r}
hist(wine_data1$quality, xlab= "Quality", main = "Histogram of White Wine Quality")
hist(wine_data2$quality, xlab= "Quality", main = "Histogram of Red Wine Quality")

```

```{r}
wine_data1$quality = ifelse(wine_data1$quality < 5, 'low', ifelse(wine_data1$quality > 7, 'high', 'medium'))
wine_data1$quality = ordered(wine_data1$quality, c('low', 'medium', 'high'))

wine_data2$quality = ifelse(wine_data2$quality < 5, 'low', ifelse(wine_data2$quality > 7, 'high', 'medium'))
wine_data2$quality = ordered(wine_data2$quality, c('low', 'medium', 'high'))

```

```{r}
norm = function(x) {
  return ((x - min(x)) / (max(x) - min(x)))
  }
wine_data3 = as.data.frame(sapply(wine_data1[-12],norm))
wine_data4 = as.data.frame(sapply(wine_data2[-12],norm))
```

```{r}
wine_data3$quality <- wine_data1$quality
train_ind1 = sample(nrow(wine_data1), 0.7 * nrow(wine_data1))
train1 = wine_data3[train_ind1,]
test1 = wine_data3[-train_ind1,]
train_labels1 = wine_data1[train_ind1,12]
test_labels1 = wine_data1[-train_ind1, 12]
wine_prediction <- knn(train1, test1, train_labels1, 5)

wine_data4$quality <- wine_data2$quality
train_ind2 = sample(nrow(wine_data2), 0.7 * nrow(wine_data2))
train2 = wine_data4[train_ind2,]
test2 = wine_data4[-train_ind2,]
train_labels2 = wine_data2[train_ind2,12]
test_labels2 = wine_data2[-train_ind2, 12]
wine_prediction2 <- knn(train2, test2, train_labels2, 5)

```

```{r}
library(caret)
cm1 = confusionMatrix(as.factor(test_labels1), as.factor(wine_prediction))
cm1

cm2 = confusionMatrix(as.factor(test_labels2), as.factor(wine_prediction))
cm2



```

